#!/usr/bin/env php
<?php

use Illuminate\Foundation\Application;
use Symfony\Component\Console\Input\ArgvInput;

define('LARAVEL_START', microtime(true));

ini_set('pcre.backtrack_limit', (string) max(100000000, (int) ini_get('pcre.backtrack_limit')));
ini_set('pcre.recursion_limit', (string) max(100000000, (int) ini_get('pcre.recursion_limit')));

// Register the Composer autoloader...
require __DIR__.'/vendor/autoload.php';

// Bootstrap Laravel and handle the command...
/** @var Application $app */
$app = require_once __DIR__.'/bootstrap/app.php';

$status = $app->handleCommand(new ArgvInput);

exit($status);
