<!DOCTYPE html>
<html>
<head>
    <title>UPAS Report Export</title>
    <style>
        body { font-family: Arial, sans-serif; margin: 20px; }
        table { width: 100%; border-collapse: collapse; margin-top: 20px; }
        th, td { border: 1px solid #ddd; padding: 8px; text-align: left; }
        th { background-color: #f2f2f2; }
        h1 { color: #333; }
    </style>
</head>
<body>
    <h1>UPAS Report Export</h1>
    <p>Generated on: {{ now()->format('Y-m-d H:i:s') }}</p>
    <p>Generated by: {{ $user->name }}</p>
    
    <table>
        <thead>
            <tr>
                <th>Submission ID</th>
                <th>Template Code</th>
                <th>SG Code</th>
                <th>KRA Title</th>
                <th>KPI Title</th>
                <th>Campus</th>
                <th>Quarter</th>
                <th>Status</th>
                <th>Submitted By</th>
                <th>Submitted At</th>
            </tr>
        </thead>
        <tbody>
            @forelse($submissions as $submission)
            <tr>
                <td>{{ $submission->submission_id ?? $submission->id }}</td>
                <td>{{ $submission->template_code }}</td>
                <td>{{ $submission->sg_code }}</td>
                <td>{{ $submission->kra_title }}</td>
                <td>{{ $submission->kpi_title }}</td>
                <td>{{ $submission->campus }}</td>
                <td>{{ $submission->quarter }}</td>
                <td>{{ $submission->status }}</td>
                <td>{{ $submission->submitter->name ?? 'N/A' }}</td>
                <td>{{ $submission->submitted_at ? $submission->submitted_at->format('Y-m-d H:i:s') : 'N/A' }}</td>
            </tr>
            @empty
            <tr>
                <td colspan="10" style="text-align: center;">No submissions found</td>
            </tr>
            @endforelse
        </tbody>
    </table>
</body>
</html>


















