<!DOCTYPE html>
<html>
<head>
    <title>SUMMARY OF ACCOMPLISHMENTS</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 20px;
            font-size: 11px;
        }
        h1 {
            text-align: center;
            color: #333;
            margin-bottom: 10px;
            font-size: 16px;
        }
        h2 {
            color: #333;
            margin-top: 20px;
            margin-bottom: 10px;
            font-size: 14px;
            border-bottom: 2px solid #333;
            padding-bottom: 5px;
        }
        .header-info {
            text-align: center;
            margin-bottom: 20px;
            font-size: 10px;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 10px;
            margin-bottom: 20px;
        }
        th, td {
            border: 1px solid #333;
            padding: 6px;
            text-align: left;
        }
        th {
            background-color: #f0f0f0;
            font-weight: bold;
            text-align: center;
        }
        .summary-table td {
            text-align: center;
        }
        .kra-code {
            font-weight: bold;
            background-color: #f9f9f9;
        }
        .footer {
            margin-top: 30px;
            font-size: 10px;
            text-align: right;
        }
        .section {
            page-break-inside: avoid;
            margin-bottom: 25px;
        }
    </style>
</head>
<body>
    <h1>SUMMARY OF ACCOMPLISHMENTS</h1>
    
    <div class="header-info">
        <p><strong>Generated on:</strong> {{ $summary['generated_at'] }}</p>
        <p><strong>Generated by:</strong> {{ $user->name ?? 'System' }}</p>
    </div>

    <!-- Overall Summary Section -->
    <div class="section">
        <h2>OVERALL SUMMARY</h2>
        <table class="summary-table">
            <thead>
                <tr>
                    <th>Total KPIs</th>
                    <th>KPIs with No Target</th>
                    <th>KPIs with No Accomplishment</th>
                    <th>KPIs Below Target</th>
                    <th>KPIs Met Target</th>
                    <th>KPIs Above Target</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>{{ $summary['overall']['total_kpis'] }}</td>
                    <td>{{ $summary['overall']['no_target'] }}</td>
                    <td>{{ $summary['overall']['no_accomplishment'] }}</td>
                    <td>{{ $summary['overall']['below_target'] }}</td>
                    <td>{{ $summary['overall']['met_target'] }}</td>
                    <td>{{ $summary['overall']['above_target'] }}</td>
                </tr>
            </tbody>
        </table>
    </div>

    <!-- Summary by KRA Section -->
    <div class="section">
        <h2>SUMMARY BY KEY RESULT AREA (KRA)</h2>
        <table>
            <thead>
                <tr>
                    <th>KRA Code</th>
                    <th>KRA Title</th>
                    <th>Total KPIs</th>
                    <th>No Target</th>
                    <th>No Accomplishment</th>
                    <th>Below Target</th>
                    <th>Met Target</th>
                    <th>Above Target</th>
                </tr>
            </thead>
            <tbody>
                @forelse($summary['by_kra'] as $kraCode => $kraData)
                <tr>
                    <td class="kra-code">{{ $kraData['kra_code'] }}</td>
                    <td>{{ $kraData['kra_title'] }}</td>
                    <td style="text-align: center;">{{ $kraData['total_kpis'] }}</td>
                    <td style="text-align: center;">{{ $kraData['no_target'] }}</td>
                    <td style="text-align: center;">{{ $kraData['no_accomplishment'] }}</td>
                    <td style="text-align: center;">{{ $kraData['below_target'] }}</td>
                    <td style="text-align: center;">{{ $kraData['met_target'] }}</td>
                    <td style="text-align: center;">{{ $kraData['above_target'] }}</td>
                </tr>
                @empty
                <tr>
                    <td colspan="8" style="text-align: center;">No KRA data available</td>
                </tr>
                @endforelse
            </tbody>
        </table>
    </div>

    <!-- Summary by Responsible Work Unit Section -->
    <div class="section">
        <h2>SUMMARY BY RESPONSIBLE WORK UNIT</h2>
        <table>
            <thead>
                <tr>
                    <th>Responsible Work Unit</th>
                    <th>Total KPIs</th>
                    <th>No Target</th>
                    <th>No Accomplishment</th>
                    <th>Below Target</th>
                    <th>Met Target</th>
                    <th>Above Target</th>
                </tr>
            </thead>
            <tbody>
                @forelse($summary['by_work_unit'] as $workUnit => $unitData)
                <tr>
                    <td><strong>{{ $unitData['work_unit'] }}</strong></td>
                    <td style="text-align: center;">{{ $unitData['total_kpis'] }}</td>
                    <td style="text-align: center;">{{ $unitData['no_target'] }}</td>
                    <td style="text-align: center;">{{ $unitData['no_accomplishment'] }}</td>
                    <td style="text-align: center;">{{ $unitData['below_target'] }}</td>
                    <td style="text-align: center;">{{ $unitData['met_target'] }}</td>
                    <td style="text-align: center;">{{ $unitData['above_target'] }}</td>
                </tr>
                @empty
                <tr>
                    <td colspan="7" style="text-align: center;">No work unit data available</td>
                </tr>
                @endforelse
            </tbody>
        </table>
    </div>

    <div class="footer">
        <p>Report generated by UPAS (University Accomplishment Planning System)</p>
        <p>{{ now()->format('F d, Y \a\t h:i A') }}</p>
    </div>
</body>
</html>

